# -*- coding: utf-8 -*-
"""Analisis wilayah rawan gempa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ObzmoCOppKrSSF6kk5WGIftxge2DirI
"""

pip install geopandas shapely

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

from google.colab import drive

drive.mount('/content/drive')

"""### **Filter data dan merubah file ke csv**"""

df_gempa = pd.read_csv('/content/drive/MyDrive/Projek/dummy/gempa/katalog_gempa.tsv',sep='\t')

df_gempa.head()

df_gempa.info()

df_gempa_copy = df_gempa[['eventID','datetime','latitude','longitude','magnitude','mag_type','depth','phasecount','azimuth_gap','location','agency']].copy()

df_gempa_copy.info()

df_gempa_copy['datetime'] = pd.to_datetime(df_gempa_copy['datetime'], format='mixed', utc=True)

df_gempa_fix = df_gempa_copy[df_gempa_copy['datetime'].dt.year > 2020].copy()

df_gempa_fix

path = '/content/drive/MyDrive/Projek/dummy/gempa/geoBoundaries-IDN-ADM1.geojson'
gdf_indonesia = gpd.read_file(path)

print(gdf_indonesia['shapeName'].unique())

# Kamus translasi nama provinsi
translate_prov = {
    "Aceh": "Aceh",
    "North Sumatra": "Sumatera Utara",
    "West Sumatra": "Sumatera Barat",
    "Riau": "Riau",
    "Jambi": "Jambi",
    "South Sumatra": "Sumatera Selatan",
    "Bengkulu": "Bengkulu",
    "Lampung": "Lampung",
    "Bangka-Belitung Islands": "Kepulauan Bangka Belitung",
    "Riau Islands": "Kepulauan Riau",
    "Banten": "Banten",
    "Jakarta Special Capital Region": "DKI Jakarta",
    "West Java": "Jawa Barat",
    "Central Java": "Jawa Tengah",
    "Special Region of Yogyakarta": "DI Yogyakarta",
    "East Java": "Jawa Timur",
    "Bali": "Bali",
    "West Nusa Tenggara": "Nusa Tenggara Barat",
    "East Nusa Tenggara": "Nusa Tenggara Timur",
    "West Kalimantan": "Kalimantan Barat",
    "Central Kalimantan": "Kalimantan Tengah",
    "South Kalimantan": "Kalimantan Selatan",
    "East Kalimantan": "Kalimantan Timur",
    "North Kalimantan": "Kalimantan Utara",
    "North Sulawesi": "Sulawesi Utara",
    "Central Sulawesi": "Sulawesi Tengah",
    "South Sulawesi": "Sulawesi Selatan",
    "Southeast Sulawesi": "Sulawesi Tenggara",
    "West Sulawesi": "Sulawesi Barat",
    "Gorontalo": "Gorontalo",
    "Maluku": "Maluku",
    "North Maluku": "Maluku Utara",
    "West Papua": "Papua Barat",
    "Papua": "Papua"
}

gdf_indonesia['shapeName'] = gdf_indonesia['shapeName'].map(translate_prov)

print(gdf_indonesia['shapeName'].unique())

geometry = [Point(xy) for xy in zip(df_gempa_fix['longitude'], df_gempa_fix['latitude'])]
gdf_gempa = gpd.GeoDataFrame(df_gempa_fix, geometry=geometry, crs="EPSG:4326")

gdf_gempa_prov_indo = gpd.sjoin(gdf_gempa, gdf_indonesia, how="left", predicate="within")
gdf_gempa_prov_indo.head()

gdf_gempa_prov_indo = gdf_gempa_prov_indo.dropna(subset=['shapeName'])

gdf_gempa_prov_indo.groupby('shapeName')['eventID'].count()

gdf_gempa_prov_indo.head()

gdf_gempa_prov_indo.shape

gdf_gempa_prov_indo.to_csv('/content/drive/MyDrive/Projek/dummy/gempa/df_gempa_prov_indo.csv', index=False)

gdf_jabar = gdf_gempa_prov_indo[gdf_gempa_prov_indo['shapeName'].str.contains('Jawa Barat', case=False, na=False)]

gdf_jabar.rename(columns={'shapeName': 'provinsi'}, inplace=True)
gdf_jabar = gdf_jabar.drop(columns=['index_right','shapeISO','shapeID','shapeGroup','shapeType'])

gdf_jabar.head()

print(f"Jumlah baris: {len(gdf_jabar)}")

# Simpan ulang sebagai CSV
gdf_jabar.to_csv('/content/drive/MyDrive/Projek/dummy/gempa/df_gempa_jabar.csv', index=False)

"""### **Data Cleaning**"""

df_gempa = pd.read_csv('/content/drive/MyDrive/Projek/dummy/gempa/df_gempa_jabar.csv')
df_gempa

"""*Menambahkan Detail Kabupaten*"""

path = '/content/drive/MyDrive/Projek/dummy/gempa/geoBoundaries-IDN-ADM2.geojson'
gdf_indonesia = gpd.read_file(path)
gdf_indonesia.head()

kabupaten_jabar = [
    "Bandung", "Bandung Barat", "Bekasi", "Bogor", "Ciamis", "Cianjur",
    "Cirebon", "Garut", "Indramayu", "Karawang", "Kuningan",
    "Majalengka", "Pangandaran", "Purwakarta", "Subang",
    "Sukabumi", "Sumedang", "Tasikmalaya","Banjar"
]

# Filter hanya kabupaten yang ada di daftar di atas
gdf_jabar = gdf_indonesia[gdf_indonesia['shapeName'].isin(kabupaten_jabar)]

# Cek hasil
print("Jumlah kab/kota Jawa Barat:", len(gdf_jabar))
print(gdf_jabar[['shapeName', 'geometry']].head())

geometry = [Point(xy) for xy in zip(df_gempa['longitude'], df_gempa['latitude'])]
gdf_join = gpd.GeoDataFrame(df_gempa, geometry=geometry, crs="EPSG:4326")

gdf_gempa = gpd.sjoin(gdf_join, gdf_jabar, how="left", predicate="within")

gdf_gempa.isna().sum(axis=0)

gdf_gempa = gdf_gempa.dropna(subset=['magnitude', 'mag_type','shapeID',])

gdf_gempa.isna().sum(axis=0)

gdf_gempa.describe()

gdf_gempa['eventID'].value_counts()

gdf_gempa.duplicated().sum()

gdf_gempa['datetime'] = pd.to_datetime(gdf_gempa['datetime'], format='mixed', utc=True)
gdf_gempa.info()

gdf_gempa['datetime'] = gdf_gempa['datetime'].dt.tz_convert('Asia/Jakarta')
gdf_gempa['date'] = gdf_gempa['datetime'].dt.date
gdf_gempa['time'] = gdf_gempa['datetime'].dt.time

gdf_gempa.head()

cols = gdf_gempa.columns.tolist()

new_order = ['eventID', 'date', 'time'] + [col for col in cols if col not in ['eventID', 'date', 'time']]
df_gempa = gdf_gempa[new_order]

df_gempa = df_gempa.drop(columns=['datetime','time','location','shapeISO','shapeGroup'])
df_gempa.head()

df_gempa.rename(columns={'shapeName': 'kabupaten'}, inplace=True)

"""*Eksplorasi Data*"""

gempa_terkuat = df_gempa.nlargest(5, 'magnitude')
gempa_terkuat

# Mencari nilai min dan max dari 'mag'
min_mag = df_gempa['magnitude'].min()
max_mag = df_gempa['magnitude'].max()
print ('magnitudo terkecil:', min_mag)
print ('magnitudo terbesar:', max_mag)

# Keterangan gempa berdasarkan magnitudo
bins = [float('-inf'), 3.0, 4.0, float('inf')]  # Defining bin edges
labels = ['Kecil', 'Sedang', 'Kuat']  # Labels for the groups
df_gempa['keterangan'] = pd.cut(df_gempa['magnitude'], bins=bins, labels=labels, right=False)  # Group by mag
print(df_gempa[['date', 'magnitude', 'keterangan']])

df_gempa.value_counts('keterangan')

df_gempa.head()

# Simpan csv
df_gempa.to_csv('/content/drive/MyDrive/Projek/dummy/gempa/df_gempa_jabar_cleaned.csv', index=False)

"""### **Clustering**"""

df_gempa = pd.read_csv('/content/drive/MyDrive/Projek/dummy/gempa/df_gempa_jabar_cleaned.csv')
df_gempa.head()

df_cluster_summary = (
    df_gempa.groupby('kabupaten')
    .agg(
        jumlah_gempa=('eventID', 'count'),
        rata2_magnitude=('magnitude', 'mean'),
        highest_magnitude=('magnitude', 'max'),
        avg_lat=('latitude', 'mean'),
        avg_lon=('longitude', 'mean')
    )
    .reset_index()
)

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

X = df_cluster_summary[['jumlah_gempa', 'rata2_magnitude', 'highest_magnitude']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42)
df_cluster_summary['cluster'] = kmeans.fit_predict(X_scaled)

cluster_order = df_cluster_summary.groupby('cluster')['highest_magnitude'].mean().sort_values().index

cluster_labels = {cluster_order[0]: 'Rawan Rendah', cluster_order[1]: 'Rawan Sedang', cluster_order[2]: 'Rawan Tinggi'}

df_cluster_summary['cluster_dominan'] = df_cluster_summary['cluster'].map(cluster_labels)

df_cluster_summary

# Urutkan ulang cluster agar 0=Rendah, 1=Sedang, 2=Tinggi
order_mapping = {old: new for new, old in enumerate(cluster_order)}

df_cluster_summary['cluster'] = df_cluster_summary['cluster'].map(order_mapping)

# Ganti label berdasarkan urutan baru
label_mapping = {0: 'Rawan Rendah', 1: 'Rawan Sedang', 2: 'Rawan Tinggi'}
df_cluster_summary['cluster_dominan'] = df_cluster_summary['cluster'].map(label_mapping)

df_cluster_summary

df_cluster_summary.to_csv('/content/drive/MyDrive/Projek/dummy/gempa/df_gempa_jabar_processed.csv', index=False)

"""*Membuat file geojson*"""

gdf_indonesia = gpd.read_file("/content/drive/MyDrive/Projek/dummy/gempa/geoBoundaries-IDN-ADM2.geojson")

kabupaten_jabar = [
    "Bandung", "Bandung Barat", "Bekasi", "Bogor", "Ciamis", "Cianjur",
    "Cirebon", "Garut", "Indramayu", "Karawang", "Kuningan",
    "Majalengka", "Pangandaran", "Purwakarta", "Subang",
    "Sukabumi", "Sumedang", "Tasikmalaya"
]

gdf_jabar = gdf_indonesia[gdf_indonesia['shapeName'].isin(kabupaten_jabar)]

gdf_jabar.rename(columns={'shapeName': 'kabupaten'}, inplace=True)

gdf_final = gdf_jabar.merge(df_cluster_summary, on='kabupaten', how='left')

gdf_final

gdf_final.to_file("/content/drive/MyDrive/Projek/dummy/gempa/gempa_jabar_polygon.geojson", driver="GeoJSON")

print(gdf_final.geom_type.value_counts())

"""### **Visualisasi**"""

import matplotlib.pyplot as plt

gempa_per_prov = gdf_gempa_prov_indo['shapeName'].value_counts().reset_index()
gempa_per_prov.columns = ['shapeName', 'jumlah_gempa']

gempa_per_prov = gempa_per_prov.sort_values(by='jumlah_gempa', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=gempa_per_prov, x='jumlah_gempa', y='shapeName', palette='viridis')

plt.title('Jumlah Gempa per Provinsi (2021–2025)', fontsize=14)
plt.xlabel('Jumlah Gempa')
plt.ylabel('Provinsi')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

geometry = [Point(xy) for xy in zip(df_gempa['longitude'], df_gempa['latitude'])]
gdf_gempa = gpd.GeoDataFrame(df_gempa, geometry=geometry, crs="EPSG:4326")

fig, ax = plt.subplots(figsize=(8, 8))
gdf_jabar.plot(ax=ax, color='lightgrey', edgecolor='black')
gdf_gempa.plot(ax=ax, color='red', markersize=5)
plt.title("Sebaran Gempa di Jawa Barat (2021–2025)")
plt.show()

gempa_per_kab = df_gempa['kabupaten'].value_counts().reset_index()
gempa_per_kab.columns = ['kabupaten', 'jumlah_gempa']

gempa_per_kab = gempa_per_kab.sort_values(by='jumlah_gempa', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=gempa_per_kab, x='jumlah_gempa', y='kabupaten', palette='viridis')

plt.title('Jumlah Gempa per Kabupaten di Jawa Barat (2021–2025)', fontsize=14)
plt.xlabel('Jumlah Gempa')
plt.ylabel('Kabupaten/Kota')
plt.tight_layout()
plt.show()

df_gempa['date'] = pd.to_datetime(df_gempa['date'])
df_gempa['year'] = df_gempa['date'].dt.year

plt.figure(figsize=(8,5))
sns.histplot(df_gempa['year'], bins=range(2021, 2027), kde=False, color='steelblue')
plt.title('Jumlah Gempa per Tahun (2021–2025)')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Gempa')
plt.xticks(range(2021, 2026))
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Hitung jumlah data di setiap kategori
keterangan_counts = df_gempa['keterangan'].value_counts()

# Buat plot bar menggunakan Matplotlib
plt.figure(figsize=(8, 6))
sns.barplot(x=keterangan_counts.index, y=keterangan_counts.values, palette="viridis")
plt.title('Distribusi Keterangan', fontsize=16)
plt.xlabel('Keterangan', fontsize=14)
plt.ylabel('Jumlah', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.show()

sns.histplot(df_gempa['magnitude'], bins=20, kde=True)
plt.title('Distribusi Magnitudo Gempa Jawa Barat')

